### ISSUE TITLE
Is it possible to enforce naming?

### ISSUE THREAD

**Issue by lifeart** [crashco/ember-template-component-import#1]
* Camelized imports
* No `.-_` in names
throw error on: 
```hbs
{{impot fooBar from 'my-component'}}
{{impot this from 'my-component'}}
{{impot attrs from 'my-component'}}
{{impot Foo-Bar from 'my-component'}}
{{impot Foo.Bar from 'my-component'}}
```

allow: 
```hbs
{{import FooBar from 'my-component'}}
```

**Comment by davewasmer** [comment]
Certainly doable!

I'd suggest looking at these lines:

https://github.com/crashco/ember-template-component-import/blob/df6d5076ef0f654c37d883d93c1aff4a17521a87/index.js#L41-L59

The `localName` variable there will be the name you gave the import (i.e. `{{import <this part> ...`). We could easily examine the `localName` there and throw if there is an invalid name.

At a minimum we should probably ensure a valid Handlebars identifier, and not something `this` or `attrs`. I _think_ we're also safe to require title-case naming (i.e. `FooBar`), since the only use for this addon is to use angle bracket components, and that's a requirement for them anyway.

If there are other rules that folks would like to see, perhaps something more linter-like, we could always add options to the addon to enable/disable those as well.

Unfortunately, I'm a bit swamped at the moment, but PRs would be happily accepted for any of this! Otherwise, I'll add it when I get some spare time.

**Comment by lifeart** [comment]
@davewasmer thank you for scope clarification! 
Any public way to throw errors?

**Comment by lifeart** [comment]
https://github.com/crashco/ember-template-component-import/pull/2
